blog/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from .views import (
    BlogListView, BlogCreateView, BlogParaCreateView, BlogDetailView, BlogUpdateView, stream_file, OwnerListView, ParaUpdateView, OwnerDetailView, ParaAddView, 
    DeleteBlogView, DeleteParaView, DeletePictureView, CommentView, CommentDeleteView, AddBookmark, DeleteBookmark, AddDislike, AddLike, DeleteLike, CoverPhotoView,
    stream_cover_pic, DeleteCoverPhotoView
)


app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('picture/<int:pk>/', BlogParaCreateView.as_view(), name='blog_picture'),
    path('details/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('pic/<int:pk>/', stream_file, name='stream_pic'),
    path('owner_list/', OwnerListView.as_view(), name='owner_list'),
    path('pic_update/<int:pid>/<int:bid>/', ParaUpdateView.as_view(), name='picture_update'),
    path('owner_detail/<int:pk>/', OwnerDetailView.as_view(), name='owner_detail'),
    path('add_para/<int:bid>/', ParaAddView.as_view(), name='add_para'),
    path('blog_delete/<int:pk>/', DeleteBlogView.as_view(template_name = 'blog/delete.html', success_url=reverse_lazy('blog:owner_list')), name='blog_delete'),
    path('para_delete/<int:pk>/', DeleteParaView.as_view(), name='para_delete'),
    path('picture_delete/<int:pk>/', DeletePictureView.as_view(), name='picture_delete'),
    path('add_comment/<int:pk>/', CommentView.as_view(), name='add_comment'),
    path('comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('blog/bookmark_add/<int:pk>/', AddBookmark.as_view(), name='bookmark_add'),
    path('blog/bookmark_delete/<int:pk>/', DeleteBookmark.as_view(), name='bookmark_delete'),
    path('blog/like_delete/<int:pk>/', DeleteLike.as_view(), name='like_delete'),
    path('blog/like_add/<int:pk>/', AddLike.as_view(), name='like_add'),
    path('blog/dislike_add/<int:pk>/', AddDislike.as_view(), name='dislike_add'),
    path('blog_cover_photo/<int:pk>/', CoverPhotoView.as_view(), name='blog_cover_photo'),
    path('cover_pic/<int:pk>/', stream_cover_pic, name='stream_cover_pic'),
    path('delete_cover_photo/<int:pk>/', DeleteCoverPhotoView.as_view(), name='delete_cover_photo'),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("blog/", include('blog.urls')),
    path("user_profile/", include('user_profile.urls')),
    path("chat/", include('chat.urls')),
    path("notification/", include('notification.urls')),
    path("api/", include('blog_api.urls')),
    path("dashboard/", include('dashboard.urls')),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import RegisterView, HomepageView

app_name = 'home'
urlpatterns = [
    path('', HomepageView.as_view(), name='all'),
    path('register', RegisterView.as_view(), name='register'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class UserUuid(models.Model):
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_uuid')

    def __str__(self) -> str:
        return str(self.uuid)

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

home/views.py
"""
HOME VIEW MODULE
----------------
This module is use to store all views related to Home app
"""

import imp
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import RegistrationForm
from django.urls import reverse_lazy
from user_profile.models import ProfilePic
from django.contrib.auth.models import User
from blog.models import Blog, Bookmark, Category, LikeCat, Like
from .models import UserUuid
from blog.tests import pint
from django.db.models import Count
import asyncio
from blogger.tasks import test_funk
from django.core.paginator import Paginator
from blog.views import PaginationView
from asgiref.sync import sync_to_async

class RegisterView(View):
    """A view for regestring new users"""

    sucess_url = reverse_lazy('home:all')

    def get(self, request):
        """
        Displays a RegistrationForm

        :praram ASGIRequest request: request object
        :context: 
            fm: an instance of form class RegistrationForm
        :return: HttpResponse
        """


        fm = RegistrationForm()
        return render(request, 'home/register.html', {'fm':fm})
    
    
    def post(self, request):
        """
        Creats a User using RegistrationForm

        :praram ASGIRequest request: request object
        :context: 
            fm: an instance of form class RegistrationForm
        :return if form is valid: HttpResponse
        :return if from is not valid: HttpResponseRedirect
        """


        fm = RegistrationForm(request.POST)
        if fm.is_valid():
            user = fm.save()
            uuid = UserUuid(user=user) #creating uuid id for this user
            uuid.save()
            pic = ProfilePic(owner=user) #cerating a blank user profile pic
            pic.save() #saving a blank user profile pic
            return redirect(self.sucess_url)
        return render(request, 'home/register.html', {'fm':fm})



class HomepageView(PaginationView):
    """A view for displaying home page."""

    async def get(self, request):
        """
        Displays home page

        :praram ASGIRequest request: request object
        :context: 
            count_list: an instance of model class Category
        :return: HttpResponse
        """

        if request.user.is_authenticated:
            count_list = await sync_to_async(Category.recomendations.user_recomendation)(request.user.id) #coustom manager method 
            
        else:
             count_list = await sync_to_async(list)(Category.recomendations.anonymous_recomendation()) #coustom manager method
        
        paginator = Paginator(count_list, 2)
        page = request.GET.get("page")
        page_obj = paginator.get_page(page)
        page_lis = await self.helper_page_no(page_obj.number, paginator.num_pages)
        next_page, previous_page = await self.helper_next_page(page_obj)
             
        ctx = {"final_list":page_obj, "total_pages":page_lis, "next_page":next_page, "previous_page":previous_page}
        return await sync_to_async(render)(request, 'home/home.html', ctx)

home/templates/home/home.html
{% extends "base.html" %}
{% block navbar %}
<li class="nav-item">
    <a class="nav-link" href = "{% url 'home:register' %}?next={{request.path}}"> Sign up </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:blog_list' %}">Blogs</a>
</li>
{% endblock %}
{% block content %}
        <h1>Welcome to Blogger</h1> 
        {% for blog in final_list %}
                <div class="card" style="width: 18rem; margin-top: 2mm;">
                        <img src="{% url 'blog:owner_detail' blog.id %}" class="card-img-top" alt="...">
                        <div class="card-body">
                        <h5 class="card-title">{{ blog.b_name  }}</h5>
                        <p class="card-text"></p>
                        <a href="{% url 'blog:blog_detail' blog.id %}" class="btn btn-primary">Read</a>
                        </div>
                </div>
        {% endfor %}

        <nav aria-label="...">
                <ul class="pagination">
                    {% if previous_page %}
                    <li class="page-item">
                        <a class="page-link" href="http://127.0.0.1:8000/?page={{previous_page}}" tabindex="-1">Previous</a>
                    </li>
                    {% endif %}
                    {% for i in total_pages %}
                    {% if current_page == i %}
                        <li class="page-item active">
                            <a class="page-link" href="http://127.0.0.1:8000/?page={{i}}">{{i}} <span class="sr-only">(current)</span></a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="http://127.0.0.1:8000/?page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endfor %}
                    
                    {% if next_page %}
                    <li class="page-item">
                        <a class="page-link" href="http://127.0.0.1:8000/?page={{next_page}}">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
{% endblock %}

home/templates/home/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
        <h1> Register </h1>
        <form method="POST">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Register">
            <input type="submit" value="Cancel" onclick="window.location.href='{% url 'home:all' %}';return false;">
        </form>
{% endblock %}