blog/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from .views import (
    BlogListView, BlogCreateView, BlogParaCreateView, BlogDetailView, BlogUpdateView, stream_file, OwnerListView, ParaUpdateView, OwnerDetailView, ParaAddView, 
    DeleteBlogView, DeleteParaView, DeletePictureView, CommentView, CommentDeleteView, AddBookmark, DeleteBookmark, AddDislike, AddLike, DeleteLike, CoverPhotoView,
    stream_cover_pic, DeleteCoverPhotoView
)


app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('picture/<int:pk>/', BlogParaCreateView.as_view(), name='blog_picture'),
    path('details/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('pic/<int:pk>/', stream_file, name='stream_pic'),
    path('owner_list/', OwnerListView.as_view(), name='owner_list'),
    path('pic_update/<int:pid>/<int:bid>/', ParaUpdateView.as_view(), name='picture_update'),
    path('owner_detail/<int:pk>/', OwnerDetailView.as_view(), name='owner_detail'),
    path('add_para/<int:bid>/', ParaAddView.as_view(), name='add_para'),
    path('blog_delete/<int:pk>/', DeleteBlogView.as_view(template_name = 'blog/delete.html', success_url=reverse_lazy('blog:owner_list')), name='blog_delete'),
    path('para_delete/<int:pk>/', DeleteParaView.as_view(), name='para_delete'),
    path('picture_delete/<int:pk>/', DeletePictureView.as_view(), name='picture_delete'),
    path('add_comment/<int:pk>/', CommentView.as_view(), name='add_comment'),
    path('comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('blog/bookmark_add/<int:pk>/', AddBookmark.as_view(), name='bookmark_add'),
    path('blog/bookmark_delete/<int:pk>/', DeleteBookmark.as_view(), name='bookmark_delete'),
    path('blog/like_delete/<int:pk>/', DeleteLike.as_view(), name='like_delete'),
    path('blog/like_add/<int:pk>/', AddLike.as_view(), name='like_add'),
    path('blog/dislike_add/<int:pk>/', AddDislike.as_view(), name='dislike_add'),
    path('blog_cover_photo/<int:pk>/', CoverPhotoView.as_view(), name='blog_cover_photo'),
    path('cover_pic/<int:pk>/', stream_cover_pic, name='stream_cover_pic'),
    path('delete_cover_photo/<int:pk>/', DeleteCoverPhotoView.as_view(), name='delete_cover_photo'),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("blog/", include('blog.urls')),
    path("user_profile/", include('user_profile.urls')),
    path("chat/", include('chat.urls')),
    path("notification/", include('notification.urls')),
    path("api/", include('blog_api.urls')),
    path("dashboard/", include('dashboard.urls')),
]

chat/urls.py
from django.urls import path
from .views import ChatView, ChatListView



app_name = 'chat'
urlpatterns = [
    path('new_chat/<str:u_uid>', ChatView.as_view(), name='new_chat'),
    path('chats/', ChatListView.as_view(), name='chat_list'),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import RegisterView, HomepageView

app_name = 'home'
urlpatterns = [
    path('', HomepageView.as_view(), name='all'),
    path('register', RegisterView.as_view(), name='register'),
]

user_profile/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    UserProfileView, ProfilePicUpdateView, profile_stream_file, ProfilePicDeleteView, OwnerAboutView, AddLikeCat, DeleteLikeCat, AddFollowView, 
    DeleteFollowView, UserProfileUpdateView, UserPasswordUpdateView, chat_profile_stream_file, DashboardDetailView
)
# from .models import Blog

app_name = 'user_profile'
urlpatterns = [
    path('', UserProfileView.as_view(), name = 'profile_page'),
    path('proflie_picture/', ProfilePicUpdateView.as_view(), name = 'profile_pic'),
    path('proflie_picture_stream/', profile_stream_file, name = 'profile_pic_stream'),
    path('proflie_picture_delete/', ProfilePicDeleteView.as_view(), name = 'delete_profile_pic'),
    path('owner_about/<int:pk>', OwnerAboutView.as_view(), name = 'owner_about'),
    path('user_add_like_cat/<int:pk>', AddLikeCat.as_view(), name = 'add_like_cat'),
    path('user_delete_like_cat/<int:pk>', DeleteLikeCat.as_view(), name = 'delete_like_cat'),
    path('user_profile/follow_add/<int:pk>', AddFollowView.as_view(), name='follow_add'),
    path('user_profile/follow_delete/<int:pk>', DeleteFollowView.as_view(), name='follow_delete'),
    path('user_profile_update/', UserProfileUpdateView.as_view(), name = 'user_update'),
    path('userpassword_update/', UserPasswordUpdateView.as_view(), name = 'password_update'),
    path('proflie_picture_stream_chat/<int:pk>', chat_profile_stream_file, name = 'profile_pic_stream_chat'),
    path('dahsboard_detail/<int:pk>', DashboardDetailView.as_view(), name = 'dashboard_detail'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Group(models.Model):
    group_name = models.CharField(max_length=550)
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1_group')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2_group')

    def __str__(self) -> str:
      return str(self.group_name)
    
    class Meta:
        unique_together = ('user1','user2')

class ChatModel(models.Model):
    message = models.TextField()
    timestamp = models.TimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_chat')
    group = models.ForeignKey('Group', on_delete=models.CASCADE, related_name='group_chat')

    def __str__(self) -> str:
        return str(self.user.first_name)
    

home/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class UserUuid(models.Model):
    uuid = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_uuid')

    def __str__(self) -> str:
        return str(self.uuid)

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from .managers import GraphManager

# Create your models here.
class ProfilePic(models.Model):
    picture = models.BinaryField(null = True, blank = True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True, help_text='The MIMEType of the file')
    owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile_pic')


class Follow(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_owner_follow')
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_follower')
    created_at = models.DateTimeField(auto_now_add=True)

    graph = GraphManager()
    objects = models.Manager()

    def __str__(self) -> str:
        return self.owner.username

    class Meta:
        unique_together = ('follower', 'owner')

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

user_profile/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile, TemporaryUploadedFile
from blog.humanise import naturalsize
from blog.tests import pint
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from django.contrib.auth.models import User
from .models import (
    ProfilePic
)

class ProfilePicForm(forms.ModelForm):
    max_upload_limit = 5*1024*1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = ProfilePic
        fields = ['picture']

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic)> self.max_upload_limit:
            self.add_error(f'file must be < {self.max_upload_limit_text} bytes')

    def save(self, commit=True):
        instance = super(ProfilePicForm, self).save(commit=False)
        f = instance.picture
        if isinstance(f,InMemoryUploadedFile) or isinstance(f, TemporaryUploadedFile):
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr
        if commit:
            instance.save()
        return instance



class UserUpdateForm(UserChangeForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

chat/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, Http404
from blog.tests import pint
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
import asyncio
from asgiref.sync import sync_to_async
from .models import Group, ChatModel
from home.models import UserUuid




class ChatView(LoginRequiredMixin, View):

    def get(self, request, u_uid):
        c_user = request.user
        uuid_c = UserUuid.objects.get(user=c_user) #current user uuid
        uuid_o = UserUuid.objects.get(uuid=u_uid) #other user uuid
        o_user = uuid_o.user #other user
        group_name, uu1, uu2 = self.sorting(uuid_o, uuid_c)
        if uu1 == uu2:
            raise Http404('you can\'t chat with yourself')
        group, t = Group.objects.get_or_create(group_name=group_name, user1=uu1, user2=uu2)
        chats = ChatModel.objects.filter(group=group)
        ctx = {'group_name':group.group_name, "chats":chats, "other_user":o_user, "user_uuid":str(uuid_c)}
        return render(request, "chat/chat.html", ctx)
    
    def sorting(self, u1, u2):
        u1 = str(u1)
        u2 = str(u2)
        lis = [u1, u2]
        lis.sort()
        uu1 = UserUuid.objects.get(uuid=lis[0])
        uu2 = UserUuid.objects.get(uuid=lis[1])
        group_name = ".".join(lis)
        pint(group_name)
        return group_name, uu1.user, uu2.user


class ChatListView(LoginRequiredMixin, View):

    def get(self, request):
        groups = Group.objects.filter(user1=request.user)|Group.objects.filter(user2=request.user)
        pint(groups)
        ctx = {"groups":groups}
        return render(request, "chat/chat_list.html", ctx)

home/views.py
"""
HOME VIEW MODULE
----------------
This module is use to store all views related to Home app
"""

import imp
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .forms import RegistrationForm
from django.urls import reverse_lazy
from user_profile.models import ProfilePic
from django.contrib.auth.models import User
from blog.models import Blog, Bookmark, Category, LikeCat, Like
from .models import UserUuid
from blog.tests import pint
from django.db.models import Count
import asyncio
from blogger.tasks import test_funk
from django.core.paginator import Paginator
from blog.views import PaginationView
from asgiref.sync import sync_to_async

class RegisterView(View):
    """A view for regestring new users"""

    sucess_url = reverse_lazy('home:all')

    def get(self, request):
        """
        Displays a RegistrationForm

        :praram ASGIRequest request: request object
        :context: 
            fm: an instance of form class RegistrationForm
        :return: HttpResponse
        """


        fm = RegistrationForm()
        return render(request, 'home/register.html', {'fm':fm})
    
    
    def post(self, request):
        """
        Creats a User using RegistrationForm

        :praram ASGIRequest request: request object
        :context: 
            fm: an instance of form class RegistrationForm
        :return if form is valid: HttpResponse
        :return if from is not valid: HttpResponseRedirect
        """


        fm = RegistrationForm(request.POST)
        if fm.is_valid():
            user = fm.save()
            uuid = UserUuid(user=user) #creating uuid id for this user
            uuid.save()
            pic = ProfilePic(owner=user) #cerating a blank user profile pic
            pic.save() #saving a blank user profile pic
            return redirect(self.sucess_url)
        return render(request, 'home/register.html', {'fm':fm})



class HomepageView(PaginationView):
    """A view for displaying home page."""

    async def get(self, request):
        """
        Displays home page

        :praram ASGIRequest request: request object
        :context: 
            count_list: an instance of model class Category
        :return: HttpResponse
        """

        if request.user.is_authenticated:
            count_list = await sync_to_async(Category.recomendations.user_recomendation)(request.user.id) #coustom manager method 
            
        else:
             count_list = await sync_to_async(list)(Category.recomendations.anonymous_recomendation()) #coustom manager method
        
        paginator = Paginator(count_list, 2)
        page = request.GET.get("page")
        page_obj = paginator.get_page(page)
        page_lis = await self.helper_page_no(page_obj.number, paginator.num_pages)
        next_page, previous_page = await self.helper_next_page(page_obj)
             
        ctx = {"final_list":page_obj, "total_pages":page_lis, "next_page":next_page, "previous_page":previous_page}
        return await sync_to_async(render)(request, 'home/home.html', ctx)

user_profile/templates/user_profile/chat.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
    <h1> Chat </h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ fm|crispy }}
        <input type="submit" value="Send">
    </form>
        {% for row in ordered_row %}
            {% if request.user == row.chat.sender %}
                <div style="text-align: right;">
                    <span style="color: green; font-size: large;">{{row.text}}</span><span style=" font-size: small;">{{row.created_at|timesince}}</span><br>
                </div>
            {% elif request.user == row.chat.receiver %}
                <div style="text-align: left;">
                    <span style="color: blue; font-size: large;">{{row.text}}</span><span style=" font-size: small;">{{row.created_at|timesince}}</span><br>
                </div>
            {% endif %}
        {% endfor %}
       
{% endblock %}

user_profile/templates/user_profile/chat_list.html
{% extends "base.html" %}
{% block content %}
        {% for row in ordered_row %}
            {% if request.user == row.sender %}
            <a href="{% url 'user_profile:chat' row.receiver.id %}">{{row.receiver.username}}</a><br>
            {% elif request.user == row.receiver %}
            <a href="{% url 'user_profile:chat' row.sender.id %}">{{row.sender.username}}</a><br>
            {% endif %}
        {% endfor %}
{% endblock %}

user_profile/templates/user_profile/dashboard_detail.html
{% extends "base.html" %}
{% block navbar %}
<li class="nav-item">
        <a class="nav-link" href = "{% url 'home:register' %}?next={{request.path}}"> Sign up </a>
</li>
<li class="nav-item">
        <a class="nav-link" href="{% url 'blog:blog_create' %}"> create a blog </a>
</li>
<li class="nav-item">
        <a class="nav-link" href="{% url 'blog:owner_list' %}">Own Blogs</a>
</li>
{% endblock %}
{% block dropdown_list %}
        <li><a class="dropdown-item" href="{% url 'user_profile:profile_pic' %}">Profile pic</a></li>
        <li><a class="dropdown-item" href="{% url 'user_profile:user_update' %}">Update Profile</a></li>
        <li><a class="dropdown-item" href="{% url 'user_profile:password_update' %}">Update Password</a></li>
{% endblock %}
{% block content %}
                <div id="totalComments" style="width:100%;max-width:700px"></div>
                <div id="totalBookmarks" style="width:100%;max-width:700px"></div>
                <div id="totalLikes" style="width:100%;max-width:700px"></div>
                <div id="totalDislikes" style="width:100%;max-width:700px"></div>
                <div id="totalViews" style="width:100%;max-width:700px"></div>

        
                
                
        
                
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <script>
                // Comments
                var com_dict = '{{ com_dict|escapejs }}';
                com_dict = JSON.parse(com_dict);

                
                
                //Bookmark
                var bookmark_dict = '{{ bookmark_dict|escapejs }}';
                bookmark_dict = JSON.parse(bookmark_dict);


                

                
                
                //Likes
                var like_dict = '{{ like_dict|escapejs }}';
                like_dict = JSON.parse(like_dict);
                


                //Views
                var view_dict = '{{ view_dict|escapejs }}';
                view_dict = JSON.parse(view_dict);
                


                function graph_func(dict_data, graph_name, y_title, tag_name){
                        var x_array = Object.keys(dict_data);
                        var y_array = Object.values(dict_data);
                        var data = [{
                                x: x_array,
                                y: y_array,
                                mode:"lines"
                        }];
                        var layout = {
                                xaxis: {range: [x_array[0], x_array[x_array.length - 1]], title: "Date"},
                                yaxis: {range: [Math.min.apply(null, y_array)-1, Math.max.apply(null, y_array)+1], title: y_title},  
                                title: graph_name
                        };
                        Plotly.newPlot(tag_name, data, layout);
                };

               
                graph_func(com_dict, "Total Comments", "Comments", "totalComments")
                graph_func(bookmark_dict, "Total Bookmarks", "Bookamrks", "totalBookmarks")
                graph_func(like_dict, "Total Likes", "Likes", "totalLikes")
                graph_func(view_dict, "Total Views", "Views", "totalViews")


                

                function favPost(url, thing_id) {
                    console.log('Requesting JSON');
                    console.log(url, thing_id);
                    $.post(url, {},  function(rowz){
                        console.log(url, 'finished');
                        $("#unfavorite_star_"+thing_id).toggle();
                        $("#favorite_star_"+thing_id).toggle();
                    }).fail(function(xhr) {
                        alert('Url failed with '+xhr.status+' '+url);
                    });
                }
                function like_data(dict_data, graph_name, y_title, tag_name, msg){
                        d = dict_data[msg.created_date]
                        console.log(typeof d)
                        if(d != undefined){
                                console.log(msg.like_value, "1")
                                if(msg.like_value){
                                        if(msg.dele){
                                                console.log("if check", "2")
                                                console.log(dict_data[msg.created_date])
                                                dict_data[msg.created_date] -= 1
                                                console.log(dict_data[msg.created_date])
                                                graph_func(dict_data, graph_name, y_title, tag_name);
                                        }
                                        else{
                                                console.log("if check","3")
                                                console.log(dict_data[msg.created_date])
                                                dict_data[msg.created_date] += 1
                                                console.log(dict_data[msg.created_date])
                                                graph_func(dict_data, graph_name, y_title, tag_name);
                                        }
                                }
                                else{
                                        console.log("if check","4")
                                        console.log(dict_data[msg.created_date])
                                        dict_data[msg.created_date] -= 1
                                        console.log(dict_data[msg.created_date])
                                        graph_func(dict_data, graph_name, y_title, tag_name);
                                };
                                
                        }
                        else{console.log("else check","5")
                                console.log(dict_data[msg.created_date])
                                dict_data[msg.created_date] = 1
                                console.log(dict_data[msg.created_date])
                                graph_func(dict_data, graph_name, y_title, tag_name);
                        };
                };


                function live_data(dict_data, graph_name, y_title, tag_name, msg){
                        d = dict_data[msg.created_date]
                        console.log(typeof d)
                        if(d != undefined){
                                if(msg.dele){
                                console.log("if check", "2")
                                console.log(dict_data[msg.created_date])
                                dict_data[msg.created_date] -= 1
                                console.log(dict_data[msg.created_date])
                                graph_func(dict_data, graph_name, y_title, tag_name);
                                }
                                else{
                                        console.log("if check","3")
                                        console.log(dict_data[msg.created_date])
                                        dict_data[msg.created_date] += 1
                                        console.log(dict_data[msg.created_date])
                                        graph_func(dict_data, graph_name, y_title, tag_name);
                                }
                        }
                        else{console.log("else check","5")
                                console.log(dict_data[msg.created_date])
                                dict_data[msg.created_date] = 1
                                console.log(dict_data[msg.created_date])
                                graph_func(dict_data, graph_name, y_title, tag_name);
                        }; 
                };
                var dashboard_websocket = new WebSocket('ws://' + window.location.host + '/ws/dashboard/');

                dashboard_websocket.onopen = function(){
                console.log("dashboard websocket conection open");
                };
                dashboard_websocket.onmessage = function (event){
                        console.log(event)
                        console.log(com_dict)
                        msg = JSON.parse(event.data)
                        var view_blog_id = '{{ blog_id|escapejs }}';
                        if(msg["blog_id"]==view_blog_id){
                                if(msg.table_name == "Commnet"){
                                        console.log("table name check")
                                        live_data(com_dict, "Total Comments", "Comments", "totalComments", msg)
                                }
                                else if(msg.table_name == "Like"){
                                        console.log("table name check")
                                        like_data(like_dict, "Total Likes", "Likes", "totalLikes", msg)}
                                        
                                else if(msg.table_name == "Bookmark"){
                                        console.log("table name check")
                                        live_data(bookmark_dict, "Total Bookmarks", "Bookmarks", "totalBookmarks", msg)
                                }
                                else if(msg.table_name == "BlogHistory"){
                                        console.log("table name check")
                                        live_data(view_dict, "Total Views", "Views", "totalViews", msg)
                                };
                        }
                        
                }
                </script>
{% endblock %}

user_profile/templates/user_profile/owner_about.html
{% extends "base.html" %}
{% block content %}
        <img style="max-width: 40mm; max-height: 40mm; display:block; margin-left: auto; margin-right: auto; float: right;" src = "{% url 'user_profile:profile_pic_stream' %}"> 
        <h1>{{ owner.username }}</h1>
        <a href="{% url 'home:all' %}">home</a>
        {% if owner.id != request.user.id %}
                <a href="{% url 'chat:new_chat' owner.user_uuid.uuid %}">Chat</a>
        {% endif %}
        {% if request.user != owner %}
                <li style="list-style:none;">
                        {% if user.is_authenticated %}
                        <span>Follow</span>
                                <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                                <a href="#" onclick=
                                "favPost('{% url 'user_profile:follow_delete' owner.id %}', {{ owner.id }} );return false;"
                                {% if request.user not in follow_list %} style="display: none;" {% endif %}
                                id="favorite_star_{{owner.id}}">
                                <span class="fa-stack" style="vertical-align: middle;">
                                <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
                                <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                                </a>
                                <!-- the second href -->
                                <a href="#" onclick=
                                "favPost('{% url 'user_profile:follow_add' owner.id %}', {{ owner.id }} );return false;"
                                {% if request.user in follow_list %} style="display: none;" {% endif %}
                                id="unfavorite_star_{{owner.id}}">
                                <span class="fa-stack" style="vertical-align: middle;">
                                <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
                                <i class="fa fa-star-o fa-stack-1x"></i>
                                </span>
                                </a>
                                <a href="{% url 'chat:new_chat' owner.user_uuid %}">chat</a>
                        {% endif %}
                </li>
        {% endif %}
            <script>
                function favPost(url, thing_id) {
                    $.post(url, {},  function(rowz){
                        $("#unfavorite_star_"+thing_id).toggle();
                        $("#favorite_star_"+thing_id).toggle();
                    }).fail(function(xhr) {
                        alert('Url failed with '+xhr.status+' '+url);
                    });
                }
                </script>
{% endblock %}

user_profile/templates/user_profile/profile_pic_create.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
        <h1> Picture Blog </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Save">
            <input type="submit" value="Done" onclick="window.location.href='{% url 'user_profile:profile_page' %}';return false;">
        </form>
{% endblock %}

user_profile/templates/user_profile/user_update.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
        <h1> Update your profile </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="Cancel" onclick="window.location.href='{% url 'user_profile:profile_page'  %}';return false;">
        </form>
{% endblock %}