blog/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from .views import (
    BlogListView, BlogCreateView, BlogParaCreateView, BlogDetailView, BlogUpdateView, stream_file, OwnerListView, ParaUpdateView, OwnerDetailView, ParaAddView, 
    DeleteBlogView, DeleteParaView, DeletePictureView, CommentView, CommentDeleteView, AddBookmark, DeleteBookmark, AddDislike, AddLike, DeleteLike, CoverPhotoView,
    stream_cover_pic, DeleteCoverPhotoView
)


app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('picture/<int:pk>/', BlogParaCreateView.as_view(), name='blog_picture'),
    path('details/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('pic/<int:pk>/', stream_file, name='stream_pic'),
    path('owner_list/', OwnerListView.as_view(), name='owner_list'),
    path('pic_update/<int:pid>/<int:bid>/', ParaUpdateView.as_view(), name='picture_update'),
    path('owner_detail/<int:pk>/', OwnerDetailView.as_view(), name='owner_detail'),
    path('add_para/<int:bid>/', ParaAddView.as_view(), name='add_para'),
    path('blog_delete/<int:pk>/', DeleteBlogView.as_view(template_name = 'blog/delete.html', success_url=reverse_lazy('blog:owner_list')), name='blog_delete'),
    path('para_delete/<int:pk>/', DeleteParaView.as_view(), name='para_delete'),
    path('picture_delete/<int:pk>/', DeletePictureView.as_view(), name='picture_delete'),
    path('add_comment/<int:pk>/', CommentView.as_view(), name='add_comment'),
    path('comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('blog/bookmark_add/<int:pk>/', AddBookmark.as_view(), name='bookmark_add'),
    path('blog/bookmark_delete/<int:pk>/', DeleteBookmark.as_view(), name='bookmark_delete'),
    path('blog/like_delete/<int:pk>/', DeleteLike.as_view(), name='like_delete'),
    path('blog/like_add/<int:pk>/', AddLike.as_view(), name='like_add'),
    path('blog/dislike_add/<int:pk>/', AddDislike.as_view(), name='dislike_add'),
    path('blog_cover_photo/<int:pk>/', CoverPhotoView.as_view(), name='blog_cover_photo'),
    path('cover_pic/<int:pk>/', stream_cover_pic, name='stream_cover_pic'),
    path('delete_cover_photo/<int:pk>/', DeleteCoverPhotoView.as_view(), name='delete_cover_photo'),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("blog/", include('blog.urls')),
    path("user_profile/", include('user_profile.urls')),
    path("chat/", include('chat.urls')),
    path("notification/", include('notification.urls')),
    path("api/", include('blog_api.urls')),
    path("dashboard/", include('dashboard.urls')),
]

user_profile/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    UserProfileView, ProfilePicUpdateView, profile_stream_file, ProfilePicDeleteView, OwnerAboutView, AddLikeCat, DeleteLikeCat, AddFollowView, 
    DeleteFollowView, UserProfileUpdateView, UserPasswordUpdateView, chat_profile_stream_file, DashboardDetailView
)
# from .models import Blog

app_name = 'user_profile'
urlpatterns = [
    path('', UserProfileView.as_view(), name = 'profile_page'),
    path('proflie_picture/', ProfilePicUpdateView.as_view(), name = 'profile_pic'),
    path('proflie_picture_stream/', profile_stream_file, name = 'profile_pic_stream'),
    path('proflie_picture_delete/', ProfilePicDeleteView.as_view(), name = 'delete_profile_pic'),
    path('owner_about/<int:pk>', OwnerAboutView.as_view(), name = 'owner_about'),
    path('user_add_like_cat/<int:pk>', AddLikeCat.as_view(), name = 'add_like_cat'),
    path('user_delete_like_cat/<int:pk>', DeleteLikeCat.as_view(), name = 'delete_like_cat'),
    path('user_profile/follow_add/<int:pk>', AddFollowView.as_view(), name='follow_add'),
    path('user_profile/follow_delete/<int:pk>', DeleteFollowView.as_view(), name='follow_delete'),
    path('user_profile_update/', UserProfileUpdateView.as_view(), name = 'user_update'),
    path('userpassword_update/', UserPasswordUpdateView.as_view(), name = 'password_update'),
    path('proflie_picture_stream_chat/<int:pk>', chat_profile_stream_file, name = 'profile_pic_stream_chat'),
    path('dahsboard_detail/<int:pk>', DashboardDetailView.as_view(), name = 'dashboard_detail'),
]

blog/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile, TemporaryUploadedFile
from .humanise import naturalsize
from .tests import pint
from .models import (
    Blog, Category, Comment, Report, ReportCategory, History, Tag, Bookmark, Like, Para
)



class BlogForm(forms.ModelForm):
    """"Creates a form for model Blog"""
    
    class Meta:
        model = Blog
        fields = ['name', 'category', 'abstract', 'tag']
    
    

class PictureForm(forms.ModelForm):
    """"Creates a form for model Para"""

    max_upload_limit = 5*1024*1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    max_upload_words_limit = 250
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    def __init__(self, *args, **kwargs): # overiding init meathod 
        if kwargs.get('blog_id'): # creating a instance variable of blog_id 
            self.blog_id = kwargs.pop('blog_id')
        else:
            self.blog_id = None
        super(PictureForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Para
        fields = ['p_title', 'text', 'picture']

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        tex = cleaned_data.get('text')
        tex_l = tex.split(' ')
        if self.blog_id:
            para_list = Para.objects.filter(blog=self.blog_id) # getting all the para objects of a blog
            if len(para_list)+ 1 > 4:
                raise forms.ValidationError({'text':['max para limit reached']}) # checking the max limit of creating a para object
        if len(tex_l) > self.max_upload_words_limit:
            self.add_error('text', f'text must be  < {self.max_upload_words_limit}')
        if pic is None:
            return
        if len(pic)> self.max_upload_limit:
            self.add_error('picture', f'file must be < {self.max_upload_limit_text} bytes') # checking the max limit of a picture in para object
        
    
    def save(self, commit=True):
        instance = super(PictureForm, self).save(commit=False)
        f = instance.picture
        if isinstance(f, InMemoryUploadedFile) or isinstance(f, TemporaryUploadedFile):
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr
        if commit:
            instance.save()
        return instance

class CommentForm(forms.Form):
    text = forms.CharField(max_length=256)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.db.models import Q
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django import forms
from .forms import BlogForm, PictureForm, CommentForm
from .owner import OwnerDeleteView, OwnerUpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .tests import pint
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
import asyncio
from asgiref.sync import sync_to_async
from blog.humanise import naturalsize
import json
from django.middleware.csrf import get_token
from django.core.files.uploadedfile import InMemoryUploadedFile, TemporaryUploadedFile
from django.core.paginator import Paginator
from itertools import chain
from .models import (
    Blog, Category, Comment, Report, ReportCategory, History, Tag, Bookmark, Like, Para, CoverPhoto
)

# Create your views here.

# base class
#<--------------------------------------------------------------------------------------------------------------->\
class PaginationView(View):
    
    async def helper_page_no(self, current_page, max_page):
        min_page_no = current_page - 3
        max_page_no = current_page + 3
        if min_page_no < 1 :
            min_page_no = 1
        if max_page_no > max_page:
            max_page_no = max_page
        return list(range(min_page_no, max_page_no+1))
    
    async def helper_next_page(self, page_obj):
        if page_obj.has_next():
            next_page = page_obj.next_page_number()
        else:
            next_page = False
        
        if page_obj.has_previous():
            previous_page = page_obj.previous_page_number()
        else:
            previous_page = False
        return next_page, previous_page
#<--------------------------------------------------------------------------------------------------------------->

#Blog
#<--------------------------------------------------------------------------------------------------------------->
class BlogListView(PaginationView):
    """Displays a list of blogs"""

    async def get(self, request):
        """
        Displays list of blogs.

        :praram ASGIRequest request: request object
        :context: 
            blogs: an instance of model class Blog
            fav_blogs: A list of blog IDs that user has set to favrioute
        :return: HttpResponse
        """

        blogs = await sync_to_async(Blog.objects.all)()
        search = request.GET.get("q")
        search_owner = []
        q = False
        final_list = await sync_to_async(list)(blogs)
        if search:
            search = search.replace("+", " ")
            q = search
            blogs,search_owner = await asyncio.gather(sync_to_async(Blog.objects.filter)(name__contains=search),sync_to_async(User.objects.filter)(Q(first_name__contains=search)|Q(last_name__contains=search)|Q(username__contains=search)))
            final_list = await sync_to_async(list)(chain(search_owner, blogs))
            pint(final_list)
        fav_blogs = []
        if request.user.is_authenticated:
            rows = await sync_to_async(list)(request.user.user_blog_bookmark.values('id')) # returns a list of bookmarked Blogs in form of dict objects
            fav_blogs = [row['id'] for row in rows] # creating a list of blog IDs that user has bookmarked
        paginator = Paginator(final_list, 2)
        page = request.GET.get("page")
        page_obj = paginator.get_page(page)
        page_lis = await self.helper_page_no(page_obj.number, paginator.num_pages)
        next_page, previous_page = await self.helper_next_page(page_obj)

        ctx=  {
            'fav_blogs':fav_blogs, "final_list":page_obj, "total_pages":page_lis, "current_page":page_obj.number,
              "next_page":next_page, "previous_page":previous_page, "search":q
        }
        return render(request, 'blog/list.html', ctx)
    


class BlogCreateView(LoginRequiredMixin, View):
    """Creating a new blog"""

    sucess_url = reverse_lazy('blog:blog_picture')

    def get(self, request):
        """
        Displays BlogForm

        if user tries to acesss this view without compeleting whole creation process
        this view will display the same blog the user didn't completed.

        :praram ASGIRequest request: request object
        :context: 
            fm: an instance of form class ProfilePicForm
        :return: HttpResponse
        """

        if 'pk' in request.session:
            pk = request.session['pk'] 
            blog = get_object_or_404(Blog, pk=pk, owner=self.request.user)
            fm = BlogForm(instance=blog)
        else:
            fm = BlogForm()
        return render(request, 'blog/blog_create.html', {'fm':fm})
    
    def post(self, request):
        """
        Creates new Blog
        
        also saves the user's ongoing progress of blog creation

        :praram ASGIRequest request: request object
        :context: 
            fm: an instance of form class ProfilePicForm
        :return if form is valid: HttpResponseRedirect
        :return if from is not valid: HttpResponse
        """

        if 'pk' in request.session:
            pk = request.session['pk']
            blog = get_object_or_404(Blog, pk=pk, owner=self.request.user) # creating blog object from blog id stored in session
            fm = BlogForm(request.POST, instance=blog)
        else:
            fm = BlogForm(request.POST)
        if fm.is_valid():
            row = fm.save(commit=False)
            row.owner = request.user
            row.save()
            para_create_url = reverse('blog:blog_picture', kwargs={"pk":row.id})
            request.session['pk'] = row.pk # saving current blog id in session
            pint("session created")
            pint(request.session.get("pk"), "get, session created")
            pint(request.session)
            return redirect(para_create_url)
        return render(request, 'blog/blog_create.html', {'fm':fm})


class BlogDetailView(View):
    """This view displays the detail page of blog"""

    @sync_to_async(thread_sensitive=False)
    def helper_blog(self, pk):
        """A helper method which returns Blog object using sync_to_async decorator"""

        b = get_object_or_404(Blog, pk=pk)
        return b
    
    @sync_to_async(thread_sensitive=False)
    def helper_pics(self, blog):
        """A helper method which returns list of Para objects using sync_to_async decorator"""

        p = blog.picture_blog.all()
        return list(p)
    
    @sync_to_async(thread_sensitive=False)
    def helper_comments(self, blog):
        """A helper method which returns list of Comment objects using sync_to_async decorator"""

        c = Comment.objects.filter(blog=blog.id)
        return list(c)
    
    @sync_to_async(thread_sensitive=False)
    def helper_like_blog(self, blog, request):
        """A helper method which returns list of like objects using sync_to_async decorator"""

        l = request.user.user_like.filter(blog=blog.id)
        return list(l)
    
    @sync_to_async
    def helper_blog_id(self, request, ctx):
        """A helper method which returns HttpResponse object using sync_to_async decorator"""
        return render(request, 'blog/detail.html', ctx)
    
    @sync_to_async
    def helper_like_blog_list(self, like_blogs=None):
        """A helper method which returns list of blog id which are liked by the user object using sync_to_async decorator"""
        return [b.blog.id for b in like_blogs]

    async def get(self, request, pk):
        """
        Displays a detail page Blog

        :praram ASGIRequest request: request object
        :praram int pk: primary key of model Blog
        :context: 
            fm: an instance of form class CommentForm
            pics: a list of instances of model class Para
            blog: an instance of model class Blog
            comments: a list of instances of model class Comment
            like_blogs: a list of instances of model class Like
            bl: a list of blog.id that are liked by user
            like: an instance of model class Like
        :return: HttpResponse
        """

        blog = await self.helper_blog(pk)
        pics, comments = await asyncio.gather(self.helper_pics(blog), self.helper_comments(blog))
        fm = CommentForm()
        if request.user.is_authenticated:
            like_blogs = await self.helper_like_blog(blog, request)
            if like_blogs:
                like = like_blogs[0].like
            else:
                like = None
            bl = await self.helper_like_blog_list(like_blogs)
        else:
            like_blogs = []
            bl = []
            like = None
        ctx = {'pics':pics, 'blog':blog, 'fm':fm, 'commnets':comments, 'like_blogs':like_blogs, 'bl':bl, 'l':like}
        return await self.helper_blog_id(request, ctx)
    
    

class BlogUpdateView(LoginRequiredMixin, View):
    """This view updates the blog"""

    sucess_url = reverse_lazy('blog:blog_list')

    def get(self, request, pk):
        """
        Displays a BlogForm

        :praram ASGIRequest request: request object
        :praram int pk: primary key of model Blog 
        :context: 
            fm: an instance of form class BlogForm
            blog: an instance of model class Blog
        :return: HttpResponse
        """

        blog = get_object_or_404(Blog, pk=pk, owner=self.request.user)
        fm = BlogForm(instance=blog)
        ctx = {'fm':fm, 'blog':blog.id}
        return render(request, 'blog/blog_update.html', ctx)
    
    def post(self, request, pk):
        """
        Updates the blog 

        :praram ASGIRequest request: request object
        :praram int pk: primary key of model Blog 
        :context: 
            fm: an instance of form class BlogForm

blog/templates/blog/blog_create.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
        <h1> Create Blog </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Next">
            <input type="submit" value="Cancel" onclick="window.location.href='{% url 'blog:owner_list' %}';return false;">
        </form>
{% endblock %}

blog/templates/blog/blog_picture.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
        <h1> Picture Blog </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Save">
            <input type="submit" value="Done" onclick="window.location.href='{% url 'blog:owner_detail' pk %}';return false;">
        </form>
{% endblock %} 

blog/templates/blog/blog_update.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
        <h1> Update Blog </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="Cancel" onclick="window.location.href='{% url 'blog:owner_detail' blog %}';return false;">
        </form>
{% endblock %}

blog/templates/blog/delete.html
{% extends "base.html" %}
{% block content %}
<p>
    <form method="post" action="">
        {% csrf_token %}
        <h1>Delete Ads</h1>
        <p> Are you sure you want to delete this ad? {picture} </p>
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'user_profile:profile_page' %}';return false;">
    </form>
</p>
{% endblock %}

blog/templates/blog/owner_detail.html
{% extends "base.html" %}
{% block navbar %}
<li class="nav-item">
    <a class="nav-link" href = "{% url 'blog:add_para' blog.id %}"> Add Para </a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:blog_delete' blog.id %}">Delete</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:owner_list' %}">Your Blogs</a>
</li>
{% endblock %}
{% block content %}
        <h1>{{ blog.name }}</h1>
        {% for pic in pics %}
            <div style = "text-align: center; background-color: rgba(211, 211, 211, 0.582); color: rgb(0, 183, 255); padding-top: 50px;
            padding-right: 80px;
            padding-bottom: 50px;
            padding-left: 80px;">
            <p>{{ pic.p_title }}</p>
            <p>{{ pic.text }}</p>
            </div>
            {% if pic.text %}
                <a href="{% url 'blog:picture_update' pic.id blog.id %}"  style="text-decoration: none; color: black;">
                    <i class="bi bi-pencil"></i>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                    </svg>
                </a>
                <a href="{% url 'blog:para_delete' pic.id %}"  style="text-decoration: none; color: black;">
                    <i class="bi bi-trash"></i>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                    </svg>
                </a>
                <img style=" max-width:50%; display:block; margin-left: auto; margin-right: auto;" src = "{% url 'blog:stream_pic' pic.id %}">
                {% if pic.content_type %}
                    <a href="{% url 'blog:picture_delete' pic.id %}" style="text-decoration: none; color: black;">
                        <i class="bi bi-file-earmark-x"></i>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-x" viewBox="0 0 16 16">
                            <path d="M6.854 7.146a.5.5 0 1 0-.708.708L7.293 9l-1.147 1.146a.5.5 0 0 0 .708.708L8 9.707l1.146 1.147a.5.5 0 0 0 .708-.708L8.707 9l1.147-1.146a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146z"/>
                            <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
                        </svg>
                    </a> 
                {% endif %}
            {% endif %}
        {% endfor %}<br>
        <button onclick="new_photo_form('{{ csrf_token }}', '{% url 'blog:blog_cover_photo' blog.id %}')">new photo</button>
        <button onclick="exisiting_photo_form('{{ pic_id_json }}', '{{ csrf_token }}', '{% url 'blog:blog_cover_photo' blog.id %}')">exisiting photo</button>
        <a href="{% url 'blog:delete_cover_photo' blog.id %}">
            <button>delete cover photo</button>
        </a>
        <div id="container">
            <style>
                label.selected img {
              border-color: blue;
            }
            </style>
        </div>
        <script>
            function new_photo_form(csrf_value, link) {
                // create form element
                var form = document.createElement("form");
                form.method = "POST"
                form.action = link;
                form.enctype = "multipart/form-data";
            
                // create input element and add to form
                var input = document.createElement("input");
                input.type = "file";
                input.name = "image";
                form.appendChild(input);

                // creating an input field for crsf token
                var csrf = document.createElement("input");
                csrf.type = "hidden";
                csrf.name = "csrfmiddlewaretoken";
                csrf.value = csrf_value;
                form.appendChild(csrf);
            
                // create submit button and add to form
                var submit = document.createElement("input");
                submit.type = "submit";
                submit.value = "Submit";
                form.appendChild(submit);
            
                // get container div
                var container = document.getElementById("container");
            
                // append form to container
                container.innerHTML = ""
                container.appendChild(form);
            }
            function exisiting_photo_form(pic, csrf_value, link) {
                // create form element
                var form = document.createElement("form");
                form.method = "POST";
                form.action = link;
                var my_list = JSON.parse(pic);

                for (let i of my_list){
                    // create input element and add to form
                    var label = document.createElement("label");
                    var input = document.createElement("input");
                    input.type = "radio";
                    input.id = i
                    input.value = i;
                    input.name = "pic_id";
                    var img = document.createElement("img");
                    img.src = "http://127.0.0.1:8000/blog/pic/"+i
                    img.style = "max-width:50%; display:block; margin-left: auto; margin-right: auto;"
                    img.className = "pic"
                    console.log(i)
                    img.alt = i
                    label.for = i;
                    label.style = "display:inline-block;";
                    input.style = "display: none;";
                    label.appendChild(input);
                    label.appendChild(img);
                    form.appendChild(label);
                }
                

                // creating an input field for crsf token
                var csrf = document.createElement("input");
                csrf.type = "hidden";
                csrf.name = "csrfmiddlewaretoken";
                csrf.value = csrf_value;
                form.appendChild(csrf);
                        
                
                // create submit button and add to form
                var submit = document.createElement("input");
                submit.type = "submit";
                submit.value = "Submit";
                form.appendChild(submit);
            
                // get container div
                var container = document.getElementById("container");
            
                // append form to container
                container.innerHTML = ""
                container.appendChild(form);


                //scroll to the container
                const elementY = container.getBoundingClientRect().top + window.pageYOffset;
                const speed = 15; // adjust the scrolling speed here
                const step = () => {
                    window.scrollBy(0, speed);
                    if (window.pageYOffset < elementY) {
                        setTimeout(step, 10);
                    }
                }
                step();
                
                const photos = document.querySelectorAll(".pic");
                console.log(photos)

                photos.forEach(photo => {
                photo.addEventListener("click", function() {
                    photos.forEach(photo => photo.classList.remove("selected"));
                    var unchosed_pic = document.querySelectorAll('.pic');
                    unchosed_pic.forEach(p => p.style = "max-width:50%; display:block; margin-left: auto; margin-right: auto;")
                    this.classList.add("selected");
                    var chosed_pic = document.querySelector('.selected');
                    chosed_pic.style = "outline: 4px solid #0000FF; max-width:50%; display:block; margin-left: auto; margin-right: auto;"
                    console.log("working")
                });
                });
            }  
        </script>
{% endblock %}

blog/templates/blog/owner_list.html
{% extends "base.html" %}
{% block content %}
        <h1>Blogs list</h1>
        {% if blogs %}
            {% for blog in blogs %}
            <div>
                <div class="card" style="width: 18rem;">
                    <img src="{% url 'blog:stream_cover_pic' blog.id %}" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">{{ blog.name }}</h5>
                      <p class="card-text">{{ blog.abstract }}</p>
                      <a href="{% url 'blog:owner_detail' blog.id %}" class="btn btn-primary">Read</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no blogs.</p>
        {% endif %}
{% endblock %}

blog/templates/blog/update_picture.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
        <h1> Picture Blog </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ fm|crispy }}
            <input type="submit" value="Save">
            <input type="submit" value="Cancel" onclick="window.location.href='{% url 'blog:owner_detail' blog %}';return false;">
        </form>
{% endblock %}