blog/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from .views import (
    BlogListView, BlogCreateView, BlogParaCreateView, BlogDetailView, BlogUpdateView, stream_file, OwnerListView, ParaUpdateView, OwnerDetailView, ParaAddView, 
    DeleteBlogView, DeleteParaView, DeletePictureView, CommentView, CommentDeleteView, AddBookmark, DeleteBookmark, AddDislike, AddLike, DeleteLike, CoverPhotoView,
    stream_cover_pic, DeleteCoverPhotoView
)


app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('picture/<int:pk>/', BlogParaCreateView.as_view(), name='blog_picture'),
    path('details/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('pic/<int:pk>/', stream_file, name='stream_pic'),
    path('owner_list/', OwnerListView.as_view(), name='owner_list'),
    path('pic_update/<int:pid>/<int:bid>/', ParaUpdateView.as_view(), name='picture_update'),
    path('owner_detail/<int:pk>/', OwnerDetailView.as_view(), name='owner_detail'),
    path('add_para/<int:bid>/', ParaAddView.as_view(), name='add_para'),
    path('blog_delete/<int:pk>/', DeleteBlogView.as_view(template_name = 'blog/delete.html', success_url=reverse_lazy('blog:owner_list')), name='blog_delete'),
    path('para_delete/<int:pk>/', DeleteParaView.as_view(), name='para_delete'),
    path('picture_delete/<int:pk>/', DeletePictureView.as_view(), name='picture_delete'),
    path('add_comment/<int:pk>/', CommentView.as_view(), name='add_comment'),
    path('comment_delete/<int:pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('blog/bookmark_add/<int:pk>/', AddBookmark.as_view(), name='bookmark_add'),
    path('blog/bookmark_delete/<int:pk>/', DeleteBookmark.as_view(), name='bookmark_delete'),
    path('blog/like_delete/<int:pk>/', DeleteLike.as_view(), name='like_delete'),
    path('blog/like_add/<int:pk>/', AddLike.as_view(), name='like_add'),
    path('blog/dislike_add/<int:pk>/', AddDislike.as_view(), name='dislike_add'),
    path('blog_cover_photo/<int:pk>/', CoverPhotoView.as_view(), name='blog_cover_photo'),
    path('cover_pic/<int:pk>/', stream_cover_pic, name='stream_cover_pic'),
    path('delete_cover_photo/<int:pk>/', DeleteCoverPhotoView.as_view(), name='delete_cover_photo'),
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("blog/", include('blog.urls')),
    path("user_profile/", include('user_profile.urls')),
    path("chat/", include('chat.urls')),
    path("notification/", include('notification.urls')),
    path("api/", include('blog_api.urls')),
    path("dashboard/", include('dashboard.urls')),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import RegisterView, HomepageView

app_name = 'home'
urlpatterns = [
    path('', HomepageView.as_view(), name='all'),
    path('register', RegisterView.as_view(), name='register'),
]

notification/urls.py
from django.urls import path
from .views import NotificationList, NotificationDetail

app_name = 'notification'
urlpatterns = [
    path('notification_list', NotificationList.as_view(), name='notification_list'),
    path('notification_detail/<int:pk>', NotificationDetail.as_view(), name='notification_detail'),
]

user_profile/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
    UserProfileView, ProfilePicUpdateView, profile_stream_file, ProfilePicDeleteView, OwnerAboutView, AddLikeCat, DeleteLikeCat, AddFollowView, 
    DeleteFollowView, UserProfileUpdateView, UserPasswordUpdateView, chat_profile_stream_file, DashboardDetailView
)
# from .models import Blog

app_name = 'user_profile'
urlpatterns = [
    path('', UserProfileView.as_view(), name = 'profile_page'),
    path('proflie_picture/', ProfilePicUpdateView.as_view(), name = 'profile_pic'),
    path('proflie_picture_stream/', profile_stream_file, name = 'profile_pic_stream'),
    path('proflie_picture_delete/', ProfilePicDeleteView.as_view(), name = 'delete_profile_pic'),
    path('owner_about/<int:pk>', OwnerAboutView.as_view(), name = 'owner_about'),
    path('user_add_like_cat/<int:pk>', AddLikeCat.as_view(), name = 'add_like_cat'),
    path('user_delete_like_cat/<int:pk>', DeleteLikeCat.as_view(), name = 'delete_like_cat'),
    path('user_profile/follow_add/<int:pk>', AddFollowView.as_view(), name='follow_add'),
    path('user_profile/follow_delete/<int:pk>', DeleteFollowView.as_view(), name='follow_delete'),
    path('user_profile_update/', UserProfileUpdateView.as_view(), name = 'user_update'),
    path('userpassword_update/', UserPasswordUpdateView.as_view(), name = 'password_update'),
    path('proflie_picture_stream_chat/<int:pk>', chat_profile_stream_file, name = 'profile_pic_stream_chat'),
    path('dahsboard_detail/<int:pk>', DashboardDetailView.as_view(), name = 'dashboard_detail'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- dj4e links -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<!-- bootstrap links -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" 
    crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
    crossorigin="anonymous"></script>
<style>

</style>

{% block head %} {% endblock %}

</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid" style="background-color: rgb(140, 161, 115); padding: 7px;">
      <a class="navbar-brand" href="{% url 'home:all' %}">BLOGGER</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        {% block navbar %}
        {% endblock %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </a>
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'user_profile:profile_page' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
              {% endif %}
              {% block dropdown_list %}
              {% endblock %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Link</a>
          </li>
        </ul>
        {% if  "/notification_list"  not in request.path and user.is_authenticated %}
          <li class="nav-item" style="list-style-type: none; padding-right: 3mm;">
            <a class="nav-link" href = "{% url 'notification:notification_list' %}">
              <span id="empty-bell">
                <i class="bi bi-bell"></i>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
              </svg>
              </span>
              <span id="full-bell" style="display: none;">
                <i class="bi bi-bell-fill"></i>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                  <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
                </svg>
              </span>
            </a>
        </li>
       {% endif %}
        <form class="d-flex" role="search" method="get" action="{% url 'blog:blog_list' %}">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit" style="background-color: transparent; border: none;" >
            <i class="bi bi-search"></i>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
              <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
            </svg>
          </button>
        </form>
      </div>
    </div>
  </nav>
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %} {% endblock %}
<script>
  var notification_websocket = new WebSocket('ws://' + window.location.host + '/ws/notification/' );
  notification_websocket.onopen = function(){
      console.log("websocket conection open");
  };
  notification_websocket.onmessage = function (event){
    var current_path = window.location.pathname
    if(!current_path.includes("/notification_list")){
      var notification_empty_bell = document.getElementById("empty-bell")
      var notification_full_bell = document.getElementById("full-bell")
      notification_empty_bell.style = "display:none;";
      notification_full_bell.style = "";
    }
    var msg = event.data;
    console.log("message received", msg, Date())}
</script>
</body>
</html>